version: '3.2'

services:
  postgres-auth:
    image: postgres
    container_name: pg-authuser
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ead-authuser
    ports:
      - "15432:5432"
    networks:
      - decoder-network

networks:
  decoder-network:
    external: true