server:
  port: 8761

spring:
  application:
    name: ead-service-registry
  output:
    ansi:
      enabled: Always

ead:
  serviceRegistry:
    username: admin
    password: 'admin'

eureka:
  client:
    register-with-eureka: false #Nao registra ele mesmo no eureka
    fetch-registry: false #Nao busca registro no eureka
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
