server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

spring:
  application:
    name: ead-api-gateway
  output:
    ansi:
      enabled: Always
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://ead-authuser-service
          predicates:
            - Path=/ead-authuser/**

        - id: course-service
          uri: lb://ead-course-service
          predicates:
            - Path=/ead-course/**

        - id: notification-service
          uri: lb://ead-notification-service
          predicates:
            - Path=/ead-notification/**
