server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/elielbatiston/ead-config-server-repo"
          default-label: main
#          username:
#          password:

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
    instance:
      hostname: localhost
